### ISSUE TITLE
Pygments and Redcarpet incompatibility 

### ISSUE THREAD

**Issue by brienna** [muan/scribble#38]
Two issues that are affecting the look of your theme: 
- You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages.
- You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st.

**Comment by muan** [comment]
Doing a round of clean up. :pray: https://github.com/muan/scribble/pull/39#issuecomment-285918524
