### ISSUE TITLE
github user page

### ISSUE THREAD

**Issue by pansypotion** [muan/scribble#50]
你好，请问我想在username.github.io用这个主题，在电脑上运行bundle exec jekyll serve -w之后一切正常但是username.github.io上面显示的却是这个样子：
<img width="446" alt="2017-08-07 5 25 41" src="https://user-images.githubusercontent.com/27702995/29033465-775dffd6-7b95-11e7-823c-0acd65b7f02c.png">
不知道是什么原因。谢谢！

**Comment by lvchen727** [comment]
I have the same problem. How did you solve the problem?
